(()=>{
'use strict';
const API_DEFAULT='https://waseshibu-progress-api.fyam8.workers.dev';
const APP_ID='english';
const STORAGE_KEY='waseshibu.adaptive.v3';
const SYNC_DB='waseshibu-progress-sync';
const SYNC_DB_VERSION=7;
const MAX_BATCH=10;
const RECONCILE_INTERVAL_MS=60_000;
const CONTROL_REFRESH_INTERVAL_MS=5*60_000;
const REQUEST_TIMEOUT_MS=15_000;
const te=new TextEncoder();
let running=false,lastControlRefreshAt=0,timer=null;

function apiBase(){return String(window.__WASESHIBU_PROGRESS_API__||API_DEFAULT).replace(/\/+$/,'')}
function canonicalize(v){return Array.isArray(v)?v.map(canonicalize):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonicalize(v[k])])):v}
const canonicalJson=v=>JSON.stringify(canonicalize(v));
async function sha256Hex(v){const d=await crypto.subtle.digest('SHA-256',te.encode(String(v)));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function randomToken(bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
async function fetchWithTimeout(url,options={}){const c=new AbortController(),id=setTimeout(()=>c.abort(),REQUEST_TIMEOUT_MS);try{return await fetch(url,{...options,signal:c.signal})}finally{clearTimeout(id)}}
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(SYNC_DB,SYNC_DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('control'))db.createObjectStore('control',{keyPath:'key'});if(!db.objectStoreNames.contains('outbox'))db.createObjectStore('outbox',{keyPath:'eventId'});if(!db.objectStoreNames.contains('deadletter'))db.createObjectStore('deadletter',{keyPath:'eventId'});if(!db.objectStoreNames.contains('seen_v2'))db.createObjectStore('seen_v2',{keyPath:'sourceKey'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('progress sync database blocked'))})}
function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'))})}
function requestValue(req){return new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function getControl(key){const db=await openDb();try{const tx=db.transaction('control','readonly'),row=await requestValue(tx.objectStore('control').get(key));await txDone(tx);return row?.value}finally{db.close()}}
async function setControl(key,value){const db=await openDb();try{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control');value==null?store.delete(key):store.put({key,value});await txDone(tx)}finally{db.close()}}
function sourceKey(id){return `${APP_ID}:${id}`}
function deviceMetadata(){const ua=String(navigator.userAgent||'');return{deviceType:/iPad|Tablet/i.test(ua)?'tablet':/Mobi|Android|iPhone/i.test(ua)?'mobile':'desktop',osFamily:/iPhone|iPad|iOS/i.test(ua)?'iOS/iPadOS':/Android/i.test(ua)?'Android':/Windows/i.test(ua)?'Windows':/Mac OS|Macintosh/i.test(ua)?'macOS':/Linux/i.test(ua)?'Linux':'unknown',browserFamily:/Edg\//i.test(ua)?'Edge':/CriOS|Chrome\//i.test(ua)?'Chrome':/FxiOS|Firefox\//i.test(ua)?'Firefox':/Safari\//i.test(ua)?'Safari':'unknown'}}
async function getOrCreateRegistrationSeed(){const db=await openDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('control','readwrite'),store=tx.objectStore('control');let result={};const regReq=store.get('registration');regReq.onsuccess=()=>{const registration=regReq.result?.value;if(registration?.credential){result={registration};return}const pendingReq=store.get('pendingRegistration');pendingReq.onsuccess=()=>{let pending=pendingReq.result?.value;if(!pending?.registrationId||!pending?.credential){pending={registrationId:crypto.randomUUID(),credential:randomToken(),createdAt:new Date().toISOString()};store.put({key:'pendingRegistration',value:pending})}result={pending}};pendingReq.onerror=()=>{try{tx.abort()}catch{}reject(pendingReq.error)}};regReq.onerror=()=>{try{tx.abort()}catch{}reject(regReq.error)};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('registration transaction aborted'))})}finally{db.close()}}
async function ensureRegistration(){if(!apiBase()||await getControl('syncRevoked'))return null;const seed=await getOrCreateRegistrationSeed();if(seed.registration?.credential)return seed.registration;const pending=seed.pending;if(!pending?.registrationId||!pending?.credential)return null;try{const r=await fetchWithTimeout(`${apiBase()}/v1/register-anonymous`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({registrationId:pending.registrationId,credentialHash:await sha256Hex(pending.credential),device:deviceMetadata()})}),d=await r.json().catch(()=>({}));if(!r.ok)return null;const reg={registrationId:pending.registrationId,credential:pending.credential,status:d.status||'unclassified',deviceCode:d.deviceCode||null,enrolledAt:new Date().toISOString()};await setControl('registration',reg);return reg}catch{return null}}
async function refreshControl(reg,force=false){if(!reg?.credential)return false;const now=Date.now();if(!force&&now-lastControlRefreshAt<CONTROL_REFRESH_INTERVAL_MS)return true;try{const r=await fetchWithTimeout(`${apiBase()}/v1/control`,{headers:{authorization:`Bearer ${reg.credential}`}}),d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);lastControlRefreshAt=now;return false}if(!r.ok)return false;const next={...reg,status:d.status||reg.status,deviceCode:d.deviceCode||reg.deviceCode};Object.assign(reg,next);await setControl('collectionDisabled',d.collectionEnabled===false);await setControl('registration',next);lastControlRefreshAt=now;return true}catch{return false}}
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');return x&&typeof x==='object'?x:null}catch{return null}}
function validIso(v){return typeof v==='string'&&Number.isFinite(Date.parse(v))&&Date.parse(v)>0?v:null}
function latestIso(values){return values.map(validIso).filter(Boolean).sort().at(-1)||null}
function eventTime(x){if(!x||typeof x!=='object')return null;return latestIso([x.gradedAt,x.answeredAt,x.updatedAt,x.completedAt,x.endedAt,x.createdAt,x.at,x.startedAt])}
function storedAttempts(s){return (Array.isArray(s?.attempts)?s.attempts:[]).filter(a=>a&&['graded','interrupted'].includes(String(a.status))&&Number.isFinite(Number(a.year)))}
function gradedAttempts(s){return storedAttempts(s).filter(a=>a.status==='graded')}
function drillRows(s){return Array.isArray(s?.drillLog)?s.drillLog.filter(Boolean):[]}
function weakRows(s){return Object.values(s?.weak||{}).filter(x=>x&&typeof x==='object')}
function weakCategorySummary(rows){const counts=new Map();for(const w of rows.filter(x=>x.status!=='mastered')){const label=String(w.category||w.skill||w.focusTag||'その他').trim();if(label)counts.set(label,(counts.get(label)||0)+1)}return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,6).map(([k,n])=>`${k}:${n}`).join(' / ').slice(0,120)}
function safeId(v,max=120){return String(v||'unknown').replace(/[^A-Za-z0-9._:-]/g,'_').slice(0,max)||'unknown'}
function drillYear(d){const m=/^(20(?:19|2[0-6])):/.exec(String(d?.key||''));return m?.[1]||null}
function buildOccurrenceRecords(s){if(!s)return[];const records=[];for(const [i,a] of storedAttempts(s).entries()){const at=eventTime(a);if(!at)continue;const graded=a.status==='graded',year=String(a.year);records.push({sourceRecordId:`history:exam:${safeId(a.id||`${year}:${at}:${i}`)}`,eventType:graded?'exam_completed':'exam_interrupted',occurredAt:at,payload:graded?{year,score:Number(a.writtenScore)||0,maxScore:80,kind:String(a.mode||a.exposure||'exam').slice(0,80),completed:true}:{year,kind:String(a.mode||a.exposure||'exam').slice(0,80),completed:false}})}for(const d of drillRows(s)){const at=eventTime(d);if(!at)continue;const year=drillYear(d),q=safeId(d.q,160);records.push({sourceRecordId:`history:drill:${safeId(at,40)}:${q}`,eventType:'drill_answered',occurredAt:at,payload:{...(year?{year}:{}),kind:'remediation-drill',skill:String(d.skill||'').slice(0,120),questionId:q,correct:d.ok?1:0,total:1,completed:true}})}return records}
function occurrenceSignature(s){const attempts=storedAttempts(s).map(a=>[a.id,a.status,eventTime(a),a.writtenScore]),drills=drillRows(s).map(d=>[d.at,d.q,d.ok,d.key]);return canonicalJson({attempts,drills})}
function buildStateRecords(s=loadState()){if(!s)return[];const attempts=storedAttempts(s),graded=gradedAttempts(s),drills=drillRows(s),weak=weakRows(s),now=new Date().toISOString(),activeAttempt=s.currentAttempt?.status==='active'?s.currentAttempt:null;const latestExam=[...graded].filter(x=>validIso(x.gradedAt||x.at)).sort((a,b)=>String(eventTime(b)).localeCompare(String(eventTime(a))))[0]||null;const lastLearningAt=latestIso([...attempts.map(eventTime),...drills.map(eventTime),activeAttempt?.startedAt]);const total=attempts.length+drills.length+(activeAttempt?1:0);const records=[{sourceRecordId:'state:summary',eventType:'progress_state',occurredAt:now,payload:{total,kind:`target-${[60,70,75].includes(Number(s.goal))?Number(s.goal):60}`,completed:false,...(lastLearningAt?{lastLearningAt}:{})}}];if(latestExam){const at=eventTime(latestExam)||now;records.push({sourceRecordId:'state:latest-exam',eventType:'exam_completed',occurredAt:at,payload:{year:String(latestExam.year),score:Number(latestExam.writtenScore)||0,maxScore:80,kind:String(latestExam.mode||latestExam.exposure||'exam').slice(0,80),completed:true,lastLearningAt:at}})}else records.push({sourceRecordId:'state:latest-exam',eventType:'exam_state',occurredAt:now,payload:{completed:false}});for(let year=2019;year<=2026;year++){const yearAttempts=attempts.filter(a=>Number(a.year)===year),yearGraded=graded.filter(a=>Number(a.year)===year),hasAnswers=Object.keys(s.answers||{}).some(k=>k.startsWith(`${year}:`))||Object.keys(s.manual||{}).some(k=>k.startsWith(`${year}:`)),started=yearAttempts.length>0||hasAnswers||Number(activeAttempt?.year)===year,completed=yearGraded.length>0;records.push({sourceRecordId:`state:year:${year}`,eventType:completed?'year_completed':'year_state',occurredAt:now,payload:started?{year:String(year),completed}:{completed:false}})}const mastered=weak.filter(x=>x.status==='mastered'),pending=weak.filter(x=>x.status==='pending');records.push({sourceRecordId:'state:weakness',eventType:'weakness_state',occurredAt:now,payload:{total:weak.length,correct:mastered.length,category:weakCategorySummary(weak),completed:weak.length>0&&mastered.length===weak.length}});records.push({sourceRecordId:'state:retention',eventType:'retention_state',occurredAt:now,payload:{total:pending.length,kind:'next-day-confirmation',completed:pending.length===0&&weak.length>0}});const lastDrillAt=latestIso(drills.map(eventTime));records.push({sourceRecordId:'state:drill',eventType:'drill_state',occurredAt:now,payload:{total:drills.length,kind:'remediation-drill',completed:false,...(lastDrillAt?{lastLearningAt:lastDrillAt}:{})}});return records}
async function queueRecord(record){const fingerprint=await sha256Hex(canonicalJson({eventType:record.eventType,occurredAt:record.occurredAt,payload:record.payload})),sourceHash=await sha256Hex(record.sourceRecordId),db=await openDb();try{const tx=db.transaction(['outbox','seen_v2'],'readwrite'),seen=tx.objectStore('seen_v2'),key=sourceKey(record.sourceRecordId),current=await requestValue(seen.get(key));if(current?.fingerprint===fingerprint){await txDone(tx);return false}const revision=Math.max(0,Number(current?.revision||0))+1,item={eventId:`${APP_ID}:${sourceHash}:r${revision}`,appId:APP_ID,sourceRecordId:record.sourceRecordId,revision,eventType:record.eventType,occurredAt:record.occurredAt,payload:record.payload,queuedAt:new Date().toISOString()};tx.objectStore('outbox').put(item);seen.put({sourceKey:key,appId:APP_ID,sourceRecordId:record.sourceRecordId,state:'queued',revision,fingerprint,at:new Date().toISOString()});await txDone(tx);return true}finally{db.close()}}
async function queueOccurrencesIfChanged(s,reg){if(!s||reg?.status!=='production')return;const signature=await sha256Hex(occurrenceSignature(s)),key=`${APP_ID}:occurrenceSignature:${reg.registrationId}`;if(await getControl(key)===signature)return;for(const record of buildOccurrenceRecords(s))await queueRecord(record);await setControl(key,signature)}
async function uploadBaseline(reg){const key=`${APP_ID}:baselineSent:${reg.registrationId}`;if(await getControl(key))return true;const s=loadState();if(!s)return true;const attempts=storedAttempts(s),graded=gradedAttempts(s),drills=drillRows(s),years={};for(const a of attempts)years[String(a.year)]=(years[String(a.year)]||0)+1;for(const d of drills){const year=drillYear(d);if(year)years[year]=(years[year]||0)+1}for(const keyName of [...Object.keys(s.answers||{}),...Object.keys(s.manual||{})]){const m=/^(20(?:19|2[0-6])):/.exec(keyName);if(m&&!years[m[1]])years[m[1]]=1}if(s.currentAttempt?.status==='active'&&Number.isFinite(Number(s.currentAttempt.year)))years[String(s.currentAttempt.year)]=(years[String(s.currentAttempt.year)]||0)+1;const payload={baseline:true,eventCount:attempts.length+drills.length+(s.currentAttempt?.status==='active'?1:0),scoredEventCount:graded.length,scoreTotal:graded.reduce((n,x)=>n+(Number(x.writtenScore)||0),0),eventsByYear:years,capturedAt:new Date().toISOString(),progressLabel:`english target ${[60,70,75].includes(Number(s.goal))?Number(s.goal):60}`,completedCount:weakRows(s).filter(x=>x.status==='mastered').length,totalCount:weakRows(s).length};try{const r=await fetchWithTimeout(`${apiBase()}/v1/progress/snapshot`,{method:'PUT',headers:{'content-type':'application/json',authorization:`Bearer ${reg.credential}`},body:JSON.stringify({appId:APP_ID,generation:1,payload})}),d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return false}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return false}if(!r.ok)return false;await setControl(key,{at:new Date().toISOString()});return true}catch{return false}}
async function readOutbox(){const db=await openDb();try{const tx=db.transaction('outbox','readonly'),rows=await requestValue(tx.objectStore('outbox').getAll());await txDone(tx);return(rows||[]).filter(x=>x?.appId===APP_ID).sort((a,b)=>String(a.queuedAt).localeCompare(String(b.queuedAt))).slice(0,MAX_BATCH)}finally{db.close()}}
async function settleBatch(doneIds,rejected,batch){const done=new Set((doneIds||[]).map(String)),rejectedRows=(rejected||[]).filter(x=>x?.eventId);if(!done.size&&!rejectedRows.length)return;const byId=new Map(batch.map(x=>[String(x.eventId),x])),db=await openDb();try{const tx=db.transaction(['outbox','deadletter'],'readwrite'),outbox=tx.objectStore('outbox'),dead=tx.objectStore('deadletter');for(const id of done)outbox.delete(id);for(const row of rejectedRows){const id=String(row.eventId);dead.put({eventId:id,code:String(row.code||'rejected'),rejectedAt:new Date().toISOString(),event:byId.get(id)||null});outbox.delete(id)}await txDone(tx)}finally{db.close()}}
async function flushBatch(reg){const batch=await readOutbox();if(!batch.length)return 0;try{const r=await fetchWithTimeout(`${apiBase()}/v1/events/batch`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${reg.credential}`},body:JSON.stringify({events:batch.map(({queuedAt,...e})=>e)})}),d=await r.json().catch(()=>({}));if(r.status===401){await setControl('syncRevoked',true);return-1}if(r.status===403&&d?.code==='collection_disabled'){await setControl('collectionDisabled',true);return-1}if(!r.ok)return-1;await settleBatch([...(d.accepted||[]),...(d.duplicate||[])],d.rejected||[],batch);return batch.length}catch{return-1}}
async function flushAvailable(reg,maxBatches=4){for(let i=0;i<maxBatches;i++){const n=await flushBatch(reg);if(n<=0)return n===0}return true}
async function syncOnce(forceControl=false){if(running||!apiBase()||navigator.onLine===false)return;running=true;try{const reg=await ensureRegistration();if(!reg?.credential)return;const controlOk=await refreshControl(reg,forceControl);if(!controlOk)return;if(await getControl('collectionDisabled'))return;const s=loadState();await uploadBaseline(reg);for(const record of buildStateRecords(s))await queueRecord(record);await queueOccurrencesIfChanged(s,reg);await flushAvailable(reg)}catch{/* Cloud sync is best-effort; studying remains local-first. */}finally{running=false}}
function start(){void syncOnce(true);timer=setInterval(()=>void syncOnce(false),RECONCILE_INTERVAL_MS);window.addEventListener('online',()=>void syncOnce(true));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void syncOnce(false)});window.addEventListener('pagehide',()=>void syncOnce(false))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
window.__WASESHIBU_ENGLISH_PROGRESS_SYNC__={sync:()=>syncOnce(true),appId:APP_ID,storageKey:STORAGE_KEY,dbName:SYNC_DB};
})();
