(()=>{"use strict";
const B=window.DRILLS||[];
const retireIds=new Set(["lsu11", "lsu12", "lsu13", "lsu14", "lsu15", "lsu16", "lsu17", "lsu18", "lsu19", "lsu20", "lsu21", "lsu22", "lsu23", "lsu24", "lsu25"]);
for(const q of B){if(retireIds.has(q.id)){q.retired=true;q.retiredBy="summary15-loop4";q.retiredReason="summary15-loop4監査: 過去問本文と比べて分量・不要情報・情報選別負荷が軽いため、既存履歴保護のため非破壊retire。";q.legacyCompletion=true;}}
const replacements=[
  {
    "id": "lsu26",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-museum-map",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nA girl named Sara visited a large science museum with her uncle on a rainy Saturday. At the entrance, he gave her a colorful map and told her to look at it whenever she felt lost. Sara was excited because the museum had a new dinosaur room, and she wanted to be the first visitor in her family to see the moving model of a giant dinosaur. While her uncle was buying tickets and asking about the restaurant, Sara ran ahead. Soon she found herself in a quiet hall full of paintings and old clocks. She asked two visitors where the dinosaur room was, but they were tourists and could not answer. She walked around for ten more minutes and almost started crying. Then she remembered the map in her pocket. She looked for the entrance mark, found the dinosaur room number, and followed the arrows. When her uncle arrived, Sara was already waiting there and smiling. She learned that a tool is useful only when people remember to use it.",
    "model": "Sara got lost in a museum after running ahead, but she remembered her map and used it to find the dinosaur room. She learned that a useful tool helps only when people use it.",
    "check": [
      "museum",
      "map",
      "got lost",
      "used tool",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約171語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】museum／map／got lost／used tool／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Sara got lost in a museum after running ahead, but she remembered her map and used it to find the dinosaur room. She learned that a useful tool helps only when people use it.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu27",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-weather-radio",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nMika lived in a mountain village where the weather changed quickly. Her family grew vegetables behind their small house, and her father always listened to a small radio before working in the fields. Mika thought the radio was old-fashioned because her phone showed colorful weather pictures and sent messages from a famous weather app. One Friday morning, her phone said it would be sunny all day, so she left the vegetable covers in the shed and went to school without checking anything else. Her father heard a warning on the radio while repairing a fence. Although he was tired, he covered half of the field by himself before lunch. In the afternoon, dark clouds suddenly came over the mountain, and heavy rain fell for almost an hour. The covered vegetables were safe, but the others were damaged. Mika apologized to her father and realized that new technology is useful, but experience and reliable information are also important. That evening, Mika wrote the two forecasts side by side in her notebook and asked her father how people in the village had predicted storms before phones became common.",
    "model": "Mika trusted her phone and thought the weather would be sunny, but her father followed a radio warning and covered their vegetables. When heavy rain came, she understood the value of experience and reliable information.",
    "check": [
      "Mika",
      "phone",
      "father",
      "radio warning",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約186語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】Mika／phone／father／radio warning／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Mika trusted her phone and thought the weather would be sunny, but her father followed a radio warning and covered their vegetables. When heavy rain came, she understood the value of experience and reliable information.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu28",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-clock-backup",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nTom was proud of the old clock in his room because it had belonged to his grandfather. Every morning, he woke up when it rang at six thirty. He liked the sound so much that he refused to use the alarm on his phone, even when his mother told him that old machines sometimes stopped. One Thursday night, Tom stayed up late preparing snacks for a school trip. Before he slept, he looked at the clock and felt sure that it would wake him as usual. However, during the night, the clock stopped because one small part inside it broke. Tom did not notice. He stayed in bed until his little sister shouted that breakfast was over. He rushed to the station with his bag, but the bus had already left. His teacher later told him that important plans need a backup. Tom still kept the clock on his desk, but after that he also set an alarm on his phone.",
    "model": "Tom depended on his old clock, but it stopped and he missed the start of a school trip. He learned that he should not rely on only one thing.",
    "check": [
      "old clock",
      "stopped",
      "missed trip",
      "backup",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約161語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】old clock／stopped／missed trip／backup／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Tom depended on his old clock, but it stopped and he missed the start of a school trip. He learned that he should not rely on only one thing.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu29",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-fruit-shops",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nTwo fruit shops stood on the same street near a busy station. One owner, Mr. Lee, spent a lot of money on bright signs, loud music, and colorful bags to attract customers. He often said that a shop only needed to look exciting. The other owner, Ms. Arai, kept her shop simple. She came early every morning, cleaned the shelves carefully, and chose fresh fruit from farmers she trusted. At first, many people visited Mr. Lee’s shop because it looked fun and children liked the music outside. However, some fruit was old, and customers slowly stopped coming back. Ms. Arai’s shop became busier because people knew that her fruit was good and her advice was honest. One evening, Mr. Lee saw a long line outside her shop and finally understood that a good appearance cannot replace honest work and trust. The next week, he removed the loud music, bought better fruit, and asked Ms. Arai how she chose her products. He also noticed that customers asked Ms. Arai questions and trusted her answers, while many visitors to his shop only took photos and left without buying much.",
    "model": "Mr. Lee attracted customers with bright signs, while Ms. Arai focused on clean shelves and good fruit. Customers gradually chose Ms. Arai’s shop, teaching Mr. Lee that trust is more important than appearances.",
    "check": [
      "two shops",
      "appearance",
      "quality",
      "customers changed",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約187語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】two shops／appearance／quality／customers changed／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Mr. Lee attracted customers with bright signs, while Ms. Arai focused on clean shelves and good fruit. Customers gradually chose Ms. Arai’s shop, teaching Mr. Lee that trust is more important than appearances.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu30",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-library-catalog",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nLeo loved reading adventure stories, but he was careless about returning library books. One afternoon, his teacher asked him to bring a book about explorers for a group project. Leo ran to the library and started looking along the shelves without checking the computer catalog. He thought he could find the book quickly because he had seen it somewhere before. After twenty minutes, he became annoyed and told the librarian that the library was too confusing. The librarian asked him for the title and typed it into the computer. The screen showed that the book was not in the adventure section but on a special display near the entrance. Leo found it in less than a minute. His friends were waiting, but they were glad he had finally brought the right book. Leo learned that searching without using available information can waste more time than asking or checking first. He also wrote the catalog number in his notebook so that his group could find the same book again later.",
    "model": "Leo could not find a library book because he searched blindly. After using the computer catalog, he found it quickly and learned that using available information saves time.",
    "check": [
      "library",
      "searched blindly",
      "catalog",
      "found quickly",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約169語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】library／searched blindly／catalog／found quickly／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Leo could not find a library book because he searched blindly. After using the computer catalog, he found it quickly and learned that using available information saves time.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu31",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-accent-speech",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nDaniel moved to a new school after living in another country for five years. He understood his classes well, but he spoke English with an accent that was different from most of his classmates. At his old school, a few students had laughed when he read aloud, so he decided to stay quiet in his new class. During group work, he wrote good ideas in his notebook but rarely shared them. One day, his history group had to give a presentation, and another student suddenly became sick. The teacher asked Daniel to explain the final part. He was nervous, but he spoke clearly and used the pictures he had prepared. His classmates listened carefully and thanked him afterward. Daniel realized that his accent did not make his ideas less valuable, and he became more willing to speak. After that day, he joined class discussions more often and even helped another new student who was afraid to speak. He also learned that classmates were more interested in the content of his explanation than in the way each word sounded.",
    "model": "Daniel stayed quiet at his new school because classmates had once laughed at his accent. After his presentation went well, he realized his ideas were valuable and became more willing to speak.",
    "check": [
      "Daniel",
      "accent",
      "kept quiet",
      "presentation",
      "changed"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約178語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】Daniel／accent／kept quiet／presentation／changed\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Daniel stayed quiet at his new school because classmates had once laughed at his accent. After his presentation went well, he realized his ideas were valuable and became more willing to speak.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu32",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-seeds",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nRina joined the gardening club because she wanted to grow sunflowers for the school entrance. The club teacher gave each student a small pot and explained that seeds needed sunlight, soil, and the right amount of water. Rina wanted her flowers to grow faster than everyone else’s, so she put her pot near the hottest window and watered it many times a day. She also covered the pot with plastic because she thought extra warmth would help. For the first few days she was proud of her careful work, but then the soil began to smell bad and the seeds did not grow. The teacher showed her that too much water and heat had made the seeds rot. Rina planted new seeds and followed the instructions this time. She learned that more help is not always better if it does not match what something really needs. Other students’ plants grew slowly but strongly, which helped Rina see why patient care was better than forcing growth.",
    "model": "Rina gave her seeds too much water and heat because she wanted them to grow quickly, but they rotted. She learned that giving more is not always giving better care.",
    "check": [
      "seeds",
      "too much water",
      "rotted",
      "proper care",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約165語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】seeds／too much water／rotted／proper care／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Rina gave her seeds too much water and heat because she wanted them to grow quickly, but they rotted. She learned that giving more is not always giving better care.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu33",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-town-traffic",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nGreenhill was a small town with heavy traffic every Saturday morning. Many cars came to the market street, and drivers often complained that there were not enough parking spaces. The town office first built a new parking area behind the post office, but the road became even more crowded because more people decided to drive. A group of junior high school students studied the problem for a class project. They counted cars, interviewed shoppers, and found that many people lived close enough to walk or cycle but drove because the bus was slow and bicycle parking was unsafe. The students suggested a shuttle bus from the station and covered bicycle stands near the market. Three months after the town tried these ideas, fewer cars entered the street and shops still had many customers. The town learned that understanding the real cause of a problem is better than adding a simple solution. Some adults were surprised that the students’ idea worked better than the expensive parking area. The students later presented their data at a town meeting, showing that careful observation could save money as well as reduce traffic.",
    "model": "Greenhill had heavy Saturday traffic, and adding parking did not help. After students studied the real causes, the town improved buses and bicycle parking, reducing cars without hurting shops.",
    "check": [
      "traffic",
      "parking failed",
      "students studied",
      "real cause",
      "solution"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約188語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】traffic／parking failed／students studied／real cause／solution\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Greenhill had heavy Saturday traffic, and adding parking did not help. After students studied the real causes, the town improved buses and bicycle parking, reducing cars without hurting shops.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu34",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-cake",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nMina wanted to bake a birthday cake for her younger brother. She had watched many cooking videos, and the cakes in them always looked perfect. On Saturday morning, her mother offered to help, but Mina said she could do everything alone. She wanted to finish before lunch, so she read the recipe quickly and placed the ingredients on the table. The sugar and salt were in similar glass jars, and Mina did not check the labels carefully. She mixed a large spoonful of salt into the cake and put it in the oven. The cake looked beautiful when it came out, and her brother clapped when he saw it. But after one bite, everyone stopped smiling. Mina felt embarrassed, but her mother kindly showed her the recipe again. Mina learned that careful preparation matters more than trying to finish quickly or make something look good. On the following weekend, she tried again, measured each ingredient slowly, and made a smaller cake that everyone enjoyed.",
    "model": "Mina hurried while baking and mistook salt for sugar, so her beautiful cake tasted bad. She learned that careful preparation is more important than speed or appearance.",
    "check": [
      "baking",
      "mistake",
      "salt",
      "looked good tasted bad",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約164語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】baking／mistake／salt／looked good tasted bad／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Mina hurried while baking and mistook salt for sugar, so her beautiful cake tasted bad. She learned that careful preparation is more important than speed or appearance.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu35",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-bird-feeder",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nThe science club at North School wanted more birds to visit the garden outside the library. The members bought a wooden bird feeder and filled it with seeds. They placed it near a bench so students could watch birds during lunch. For several days, almost no birds came, and some members said the feeder was useless. Haru, who liked observing animals, sat quietly after school and noticed two cats sleeping under the bench. He also saw that the feeder moved too much in the wind. The next week, the club moved it to a higher branch near thick bushes and added a small cover. Soon sparrows and small colorful birds began to visit every morning. The club wrote a report explaining that helping animals requires understanding their safety and habits, not just buying equipment. Students who had laughed at the project began bringing notebooks to record which birds appeared each day. Haru explained that the feeder itself had not been the problem; the place had made the birds feel unsafe.",
    "model": "A science club bought a bird feeder, but few birds came because it was placed near cats and moved in the wind. After Haru observed the problem, the club moved it and attracted birds.",
    "check": [
      "bird feeder",
      "few birds",
      "observed cause",
      "moved feeder",
      "result"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約170語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】bird feeder／few birds／observed cause／moved feeder／result\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】A science club bought a bird feeder, but few birds came because it was placed near cats and moved in the wind. After Haru observed the problem, the club moved it and attracted birds.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu36",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-bicycle-light",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nKen bought a new bicycle light because he often rode home after soccer practice. The shop assistant told him to attach it to the front of his bicycle before using it at night. Ken put the light in his school bag because he was late for practice and thought he could attach it later. After practice, his friends invited him to stop at a convenience store, and he forgot about the light. The streets were already dark when he started riding home. At a corner, a car driver did not see him until the last moment and stopped suddenly. Ken was not hurt, but he was badly frightened. When he opened his bag at home, the unused light was still there. He understood that buying safety equipment is meaningless unless people actually prepare and use it at the right time. The next morning, he attached the light carefully and checked that it worked before going to school.",
    "model": "Ken bought a bicycle light but did not attach it, so he was almost hit while riding in the dark. He learned that safety tools must be used, not just owned.",
    "check": [
      "bicycle light",
      "not attached",
      "danger",
      "safety tool",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約157語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】bicycle light／not attached／danger／safety tool／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Ken bought a bicycle light but did not attach it, so he was almost hit while riding in the dark. He learned that safety tools must be used, not just owned.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu37",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-wallet-bakery",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nAya helped at her parents’ bakery every Sunday morning. She liked talking with customers and often put her wallet on the counter when she was busy. Her mother warned her to keep it in a drawer, but Aya said everyone in the neighborhood was kind. One day the bakery was crowded because of a local festival. Aya wrapped bread, answered the phone, and showed a child where the cookies were. Later, she realized that her wallet had disappeared. She was upset and thought someone had stolen it. In the afternoon, an elderly customer returned with the wallet. He had seen it fall into a paper bag by mistake. Aya thanked him and apologized to her mother. She learned that trusting people is good, but being careless can still cause trouble for herself and others. She also made a small rule for herself: money would never be placed on the counter again, even during busy hours. Her parents were not angry, but they asked her to think about how much time everyone would have lost if the wallet had not been found.",
    "model": "Aya carelessly left her wallet on the counter while helping at a busy bakery. After a customer returned it, she learned that trust is important but carelessness can still cause trouble.",
    "check": [
      "wallet",
      "bakery",
      "careless",
      "returned",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約181語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】wallet／bakery／careless／returned／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Aya carelessly left her wallet on the counter while helping at a busy bakery. After a customer returned it, she learned that trust is important but carelessness can still cause trouble.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu38",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-piano-practice",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nYuto wanted to play a difficult piano piece at the school concert. The piece had a fast middle part that he could not play well, but he disliked practicing it because it made him feel unsuccessful. Instead, he played the easy beginning again and again. When his mother passed the room, the music sounded beautiful, so she praised him. Yuto became even more confident and told his teacher that he was ready. At the concert, he began well, and the audience listened quietly. However, when he reached the difficult middle part, his fingers stopped and he had to start again. Afterward, his teacher said that practice should focus on weak points, not only on parts that feel comfortable. Yuto was disappointed, but he understood why repeating only what he could already do had not helped him improve. For the next concert, he practiced the hardest lines first each day, even though they were not enjoyable.",
    "model": "Yuto practiced only the easy parts of a difficult piano piece and failed at the concert. He learned that real practice should focus on weak points.",
    "check": [
      "piano",
      "easy parts",
      "failed",
      "weak points",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約155語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】piano／easy parts／failed／weak points／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Yuto practiced only the easy parts of a difficult piano piece and failed at the concert. He learned that real practice should focus on weak points.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu39",
    "focusTag": "summary-2023",
    "familyId": "summary-loop4-riverbank-cleanup",
    "maxWords": 50,
    "prompt": "【オリジナル類題・2023型・50語以内】次の英文を要約しなさい。\nA dirty riverbank ran behind Sakura Junior High School. Students often saw plastic bottles and snack bags there on their way home. The student council first put up a large sign saying, “Keep Our River Clean,” but nothing changed. Some students said people were simply lazy. Others wanted to ask the city office to punish anyone who threw away trash. Before deciding, the council spent two weeks checking when and where most trash appeared. They found that many visitors ate lunch near the river on weekends, but there were no trash cans nearby and the sign was hidden behind a tree. The students cleaned the riverbank, moved the sign to a better place, and asked shops to place trash boxes near the path. A month later, the riverbank was much cleaner. The council learned that practical action based on observation works better than just blaming people. The project became a model for other classes that wanted to solve problems around the school. Teachers praised the council because the students had changed the situation by studying people’s behavior before choosing a solution.",
    "model": "A dirty riverbank did not improve with only a sign. Students observed the cause, cleaned the area, moved the sign, and added trash boxes, learning that practical action works better than blame.",
    "check": [
      "riverbank",
      "sign failed",
      "observed cause",
      "practical action",
      "result"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】50語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2023年度大問4と同じく、人物や立場の対比、変化、結論を50語以内で要約する型。\n【本文分量】約181語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】riverbank／sign failed／observed cause／practical action／result\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】A dirty riverbank did not improve with only a sign. Students observed the cause, cleaned the area, moved the sign, and added trash boxes, learning that practical action works better than blame.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  },
  {
    "id": "lsu40",
    "focusTag": "summary-2022",
    "familyId": "summary-loop4-umbrella",
    "maxWords": 40,
    "prompt": "【オリジナル類題・2022型・40語以内】次の英文を要約しなさい。\nNana’s grandmother always told her to check the weather before leaving home. Nana usually ignored this advice because she did not like carrying an umbrella. One morning, the sky was gray, but Nana was thinking about her art project and wanted to keep both hands free. Her grandmother offered her a small folding umbrella and said that rain was expected in the afternoon. Nana laughed and said the station was not far from school. During the day, the wind became stronger, and dark clouds covered the sky. After school, heavy rain began just as Nana left the gate. She tried to run to the station, but the paper bag with her notebooks became wet, and the drawings for her project were ruined. That night, Nana apologized to her grandmother and learned that a small inconvenience can prevent a much bigger problem. The next day, she placed the folding umbrella in her school bag before her grandmother said anything.",
    "model": "Nana refused to take an umbrella because it was troublesome, but heavy rain made her notebooks wet. She learned that a small inconvenience can prevent a bigger problem.",
    "check": [
      "umbrella",
      "refused",
      "rain",
      "notebooks wet",
      "lesson"
    ],
    "skill": "summary",
    "level": 3,
    "type": "selfcheck",
    "targetId": "summary-main-points",
    "examFormat": "manual",
    "sourceStyle": "2022-2023 official summary format",
    "originalDrill": true,
    "pastPaperComparison": "2022年度大問4（40語以内）または2023年度大問4（50語以内）と同じく、まとまった英文から不要情報を削り、人物・問題/変化・結果・教訓/結論を選ぶ。",
    "explanation": "【語数】40語以内。\n【設問条件】まとまった英文を読み、重要情報を選んで英語で要約する。本文の細部を全部入れない。\n【過去問比較】2022年度大問4と同じく、日常的な誤解・失敗・教訓を40語以内で要約する型。\n【本文分量】約158語。過去問本文に近づけるため、不要な細部も含めている。\n【残す要点】umbrella／refused／rain／notebooks wet／lesson\n【削る情報】固有名詞、細かな場所・時間・飾りの描写は、結論に必要な場合だけ残す。\n【構成】人物・状況 → 問題/変化 → 結果 → 教訓または結論。\n【答案例】Nana refused to take an umbrella because it was troublesome, but heavy rain made her notebooks wet. She learned that a small inconvenience can prevent a bigger problem.\n【合格戦略】A〜B。満点狙いより、主語・動詞を崩さず、原因と結論を落とさない。"
  }
];
const ids=new Set(B.map(q=>q.id));
for(const q of replacements){if(!ids.has(q.id)){B.push(q);ids.add(q.id);}}
window.DRILLS=B;
})();
