import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url),w=require('../ui/answer-widgets.js');
assert.equal(w.contractVersion,1);
const tokens=['we','had','had','enough'];
let state={order:[],missing:''};
for(const index of [0,1,2])state=w.reorderChange(state,tokens,{type:'add',index}).state;
assert.deepEqual(state.order,[0,1,2]);assert.equal(w.reorderSentence(state,tokens),'we had had');
assert.equal(w.reorderChange(state,tokens,{type:'add',index:1}).changed,false);
assert.equal(w.reorderChange(state,tokens,{type:'add',index:-1}).changed,false);
assert.equal(w.reorderChange(state,tokens,{type:'add',index:4}).changed,false);
assert.deepEqual(w.reorderChange(state,tokens,{type:'undo'}).state.order,[0,1]);
assert.deepEqual(w.reorderChange(state,tokens,{type:'clear'},{disabled:true}).state.order,[0,1,2]);
const saved=JSON.stringify(state);w.reorderChange(state,tokens,{type:'clear'});assert.equal(JSON.stringify(state),saved,'transition mutated saved draft');
assert.deepEqual(w.reorderState({order:[0,0,7,-1,'missing',2],missing:'x'},tokens).order,[0,2]);
assert.deepEqual(w.reorderState({order:[0,'missing',2],missing:'x'},tokens,{allowMissing:true}).order,[0,'missing',2]);
const opts={allowMissing:true};
assert.equal(w.reorderChange({},tokens,{type:'addMissing'},opts).error,'missing-empty');
let m=w.reorderChange({},tokens,{type:'missing',value:'word'},opts).state;
m=w.reorderChange(m,tokens,{type:'addMissing'},opts).state;
assert.equal(w.reorderSentence(m,tokens,opts),'word');
m=w.reorderChange(m,tokens,{type:'missing',value:'edited'},opts).state;
assert.equal(w.reorderSentence(m,tokens,opts),'edited');
assert.equal(w.reorderChange(m,tokens,{type:'addMissing'},opts).changed,false);
assert.deepEqual(w.reorderChange(m,tokens,{type:'clear'},opts).state,{order:[],missing:'edited'});
assert.deepEqual(w.selection(['a'],'b',{max:1}),{values:['a'],changed:false,limit:true});
assert.deepEqual(w.selection(['a'],'a',{max:1}).values,[]);
assert.deepEqual(w.selection(['a'],'b',{on:true}).values,['a','b']);
assert.deepEqual(w.selection(['a'],'a',{on:true}).values,['a']);
assert.deepEqual(w.selection(['a'],'b',{disabled:true}).values,['a']);
const a=['first'];assert.deepEqual(w.slot(a,1,'second'),['first','second']);assert.deepEqual(a,['first']);
assert.match(w.textInput({value:'"<script>',onInput:'save(this.value)'}),/&quot;&lt;script&gt;/);
assert.match(w.textInput({multiline:true,value:'</textarea><script>'}),/&lt;\/textarea&gt;&lt;script&gt;/);
const html=w.reorder({tokens,state:{order:[0]},disabled:true,handlers:{add:i=>'add('+i+')',undo:'undo()',clear:'clear()'}});
assert.equal((html.match(/disabled=""/g)||[]).length,6);
assert.ok(!html.includes('undefined'));
const root=new URL('../',import.meta.url),app=fs.readFileSync(new URL('app.js',root),'utf8'),index=fs.readFileSync(new URL('index.html',root),'utf8');
assert.ok(index.indexOf('src="ui/answer-widgets.js"')<index.indexOf('src="app.js"'));
for(const name of ['choices','textInput','slots','selection','slot','reorder','reorderChange'])assert.ok(app.includes('ANSWER_WIDGETS.'+name),name+' not delegated');
assert.doesNotMatch(fs.readFileSync(new URL('ui/answer-widgets.js',root),'utf8'),/localStorage|indexedDB|waseshibu|rikkyo|answerSpec|correctAnswer/i);
console.log('Shared answer widgets: duplicate tokens, missing word, locks, selection, drafts, escaping and delegation CLEAN');
